zuul : 
  routes : 
    passport : 
      path : /passport/**
      url : http://192.168.1.55:9090
      sensitiveHeaders: 
    product : 
      path : /product/**
      url : http://192.168.1.249:9090
      sensitiveHeaders: 
    order : 
      path : /order/**
      url : http://192.168.1.130:9090
      sensitiveHeaders: 
  
ribbon : 
  eureka : 
    enabled : false  
server :
  port : 10000
ocs :
  routes :
    - /passport/login
    - /product/
    - /order/