zuul : 
  routes : 
    passport : 
      path : /passport/**
      url : http://127.0.0.1:8088
    product : 
      path : /product/**
      url : http://127.0.0.1:9090
ribbon : 
  eureka : 
    enabled : false  
server :
  port : 10000
ocs :
  routes :
    - /passport/login
    - /product/