zuul : 
  routes : 
    passport : 
      path : /passport/**
      url : http://127.0.0.1:8088
      sensitiveHeaders: 
    product : 
      path : /product/**
      url : http://127.0.0.1:9099
      sensitiveHeaders: 
    order : 
      path : /order/**
      url : http://127.0.0.1:9090
      sensitiveHeaders: 
    words : 
      path : /words/**
      url : http://127.0.0.1:9999/words
      sensitiveHeaders: 
  
ribbon : 
  eureka : 
    enabled : false  
server :
  port : 10000
ocs :
  routes :
    - /passport/login
    - /product/
redis :
  host : 192.168.1.253
  port : 6379