zuul : 
  routes : 
    passport : 
      path : /passport/**
      url : http://localhost:8088/
      sensitiveHeaders: 
    courseunit : 
      path : /courseunit/**
      #url : http://192.168.1.249:9099
      url : http://localhost:9099/unit
      sensitiveHeaders: 
    course : 
      path : /course/**
      #url : http://10.108.25.163
      url : http://localhost:9090/
      sensitiveHeaders: 
    words : 
      path : /words/**
      url : http://127.0.0.1:9999/words
      sensitiveHeaders: 
  
ribbon : 
  eureka : 
    enabled : false  
server :
  port : 10000
ocs :
  routes :
    - /passport/login
    - /product/
redis :
  host : 192.168.1.253
  port : 6379